# Printing decorative lines and messages
print_yellow("  ———————————")
print("")
print("")
print_green("          …………………")
print_purple("   .                .            .")
print_cyan("           ydjxjnxnx")
print("")
print("         .                   .")
print("                 .                      .")
print("")
print_light_gray("   .            .")
print_light_purple("          …………………")
print_yellow("————————————-")
